services:
  - type: web
    name: Vaishanova-Web
    runtime: docker          # required for Blueprints
    plan: free
    buildCommand: mvn clean package
    dockerfilePath: ./dockerfile
    startCommand: java -jar target/VECHILE_CARE_PORTAL_APP.jar
    envVars:
      - fromGroup: VEHICLE_DB_SECRETS

databases:
  - name: VehicleDB
    engine: postgres
    plan: free
